### ISSUE TITLE
BGT Compatibility 

### ISSUE THREAD

**Issue by Salk73** [SpellholdStudios/BGGOEET#1]
Since the Forum has been down for so long now and weigo can not post updates there about his work on BGGOEET, I thought I could open an issue here to keep track of the improvements made towards full compatibility with BGT.

We might like to make a bullet point list with what was not working and is working now and what is left to do.

Thanks a lot and godspeed!

**Comment by weigo87** [comment]
That's a good idea.

BGGO should be compatible with BGT and EET. Actually, I should have all areas started once in the game for BGT and EET. Tutu and BGEE should also work, but I haven't tested them.
A few weeks ago I contacted Yovaneth. He is currently reworking the Baldurs Gate City maps. He sent them to me and I am in the process of adding the 10 areas. (BG0100, BG0200, BG0300, BG0600, BG0621, BG0700, BG0800, BG1100, BG1200, BG1300) They look fantastic. If these are put in, I'm glad for any help in testing them.
If it takes any longer at SHS we could also move to G3. There is also a thread there for BGGO.
https://www.gibberlings3.net/forums/topic/27768-baldurs-gate-graphics-overhaul-for-eet/page/5/

**Comment by Salk73** [comment]
You are doing God's work here, weigo!

I'll be very glad to test BGGO on BGT whenever you feel like you have a ready-to-go version. I had no idea that Yovaneth was in the process of reworking the Baldur's Gate City maps. I thought he retired from modding and I am very glad I was wrong.

I am aware of the thread opened at G3 and have nothing against posting there. There are in fact a couple of bug reports there from me.

The situation with the SHS Forum is quite distressing and I hope Insomniator will still be there once it's back online.

**Comment by Salk73** [comment]
The installation process fails early on BGT (I downloaded the latest master "Beta3"). The OS is Windows 10.

I have attached the debug file.

[SETUP-BGGO.DEBUG.TXT](https://github.com/SpellholdStudios/BGGOEET/files/11928858/SETUP-BGGO.DEBUG.TXT)
