### ISSUE TITLE
BGT issue: AR7800 (EBaldursGate)

### ISSUE THREAD

**Issue by TotoR115** [SpellholdStudios/BGGOEET#2]
There is a bug with AR7800 (BG0800, EBaldursGate) night map: the doors are always drawn closed even when opened. 

It is linked to AR7800N.tis wich does not have the "draw open" like other maps. EE does not have the issue.

**Comment by TotoR115** [comment]
For the record, Candles from yarls mod was not added to the friendly arm inn `FriendlyArmInn_L1,` `FriendlyArmInn_L2` and `FriendlyArmInn_L3`. 

Was it intended ?

https://github.com/Gitjas/JA-AdventurePack/blob/ffed9ae1c87b2416e0db1714a67dc1f177955df5/JA%23BGT_AdvPack/Graphical/setup-graphical.tpa#L10-L87

**Comment by weigo87** [comment]
In version 0.8.0 there is the AR6801.tph. There the torches, candles etc. are installed. 
https://www.baldurs-gate.de/index.php?resources/jarls-bgt-adventure-pack.8/

AR7800: I will solve the problem :)
Done

**Comment by TotoR115** [comment]
> In version 0.8.0 there is the AR6801.tph

Ok, next time I will use the last official version 😇. Lets just hope, it will be updated soon... or maybe the not official could be updated 😉

Joke aside, thank you!
