### ISSUE TITLE
New Ice Land night map and new Maze on BGT

### ISSUE THREAD

**Issue by TotoR115** [SpellholdStudios/BGGOEET#3]
There are issues with the modifications done to the Ice land map (ARU008) and to the maze map(ARU009):

- ARU008N.wed seems to be missing for non_ee: the game crashes when you try to enter the map.
- ARU008N.mos seems to big in comparison to the ARU008.mos, but I can't test ingame as it crash
- ARU009.mos has not the expected size. Either this mini map is too big, or the parameters are not the right ones.

**Comment by weigo87** [comment]
This was the first time I created a mos file for the oBG2 engine. That's why I didn't see that EE and non EE has different image sizes. Now the two areas should go and I have learned something again :)

**Comment by TotoR115** [comment]
Speaking of minimap size, when I updated this mod, some times ago, I'll had to resize some minimap: https://github.com/SpellholdStudios/BGGOEET/commit/ae940fb6b634fda7a5e4b2b27fbdaf3133fc5b4c

I was not proud of what I've done as I don't have the source file for those mos. I had to use NI to recreate them from the area viewer... it is clearly not perfect, but was good enough at this time.

Could you tell me if you rebuild those mos files or use the one in the repo? It could be sensible to recreate them with a better input.

In addition, for all new maps (day and night) introduce by this version (AR7300, AR7600, AR7700, AR7800, AR7900, AR8000, AR8100, AR8200, mybe more...) it could be sensible to recreate the mos as the changes are, for now, not shown on minimap

> That's why I didn't see that EE and non EE has different image sizes.

There is maybe more than that as all mos file have a different size; there are some variations for each maps... However I don't know where is defined/stored the size of the mos. If you found it then you could use a bigger/smaller mini map for area & dungeons...

**Comment by weigo87** [comment]
> Could you tell me if you rebuild those mos files or use the one in the repo? It could be sensible to recreate them with a better input.

I took all but the ice island from the old repo.
I created the ice island as follows.

1st step: original mos file exported as png with NI
2nd step: I read the size of the mos file from the original files in NI.
ee version BG1008: 200x150
non-ee: 120x90
3rd step: For BG1008 and BG1009 I scaled the png files I used to create the tis/pvrz to the size of the mos files. 
4th step: Conversion of the png files with NI into the mos format.
5th step: Packed with tileconv 

> In addition, for all new maps (day and night) introduce by this version (AR7300, AR7600, AR7700, AR7800, AR7900, AR8000, AR8100, AR8200, mybe more...) it could be sensible to recreate the mos as the changes are, for now, not shown on minimap

Should be just as feasible as described above

> There is maybe more than that as all mos file have a different size; there are some variations for each maps... However I don't know where is defined/stored the size of the mos. If you found it then you could use a bigger/smaller mini map for area & dungeons...

NOTE: if you want to create a mini-map, scale your source image by 32/3 (10.66667) for the original BG games, 32/4 for IWDs or by 6.4 for the EEs. 
https://gibberlings3.github.io/iesdp/file_formats/ie_formats/mos_v1.htm

I would just always check the size in the original  EET or BGT installation.

> In addition, for all new maps (day and night) introduce by this version (AR7300, AR7600, AR7700, AR7800, AR7900, AR8000, AR8100, AR8200, mybe more...) it could be sensible to recreate the mos as the changes are, for now, not shown on minimap

We can gradually replace all the minimaps of Baldur's Gate City with new ones.

**Comment by weigo87** [comment]
> In addition, for all new maps (day and night) introduce by this version (AR7300, AR7600, AR7700, AR7800, AR7900, AR8000, AR8100, AR8200, mybe more...) it could be sensible to recreate the mos as the changes are, for now, not shown on minimap

All Baldurs Gate City maps + Wyrms Crossing got new mos files. Both day and night.
