### ISSUE TITLE
new animations and a small visual bug in AR1304

### ISSUE THREAD

**Issue by TotoR115** [SpellholdStudios/BGGOEET#4]
Hi,

- after creating arrays that define position of candles and torches (for example: https://github.com/SpellholdStudios/BGGOEET/blob/5c7cc559d02cc27a3b0509bb239a9bd422db921f/bggo/base/animation/BaldursGateCity.tpa#L6-L7), and to avoid visual glitches in the next patched area, you need to clear the array with something like:

> 		CLEAR_ARRAY x_coord
> 		CLEAR_ARRAY y_coord

It is easily seen with ar0015 (candlekeep for BGT): With the actual version(5c7cc559d02cc27a3b0509bb239a9bd422db921f), in the top left corner, near the Inn, you can see some floating candles; they are placed at the same place they were in the previous patched area (MerchantLeague_L3).

- For oBG2 (I don't know with EE, but it should be the same) there are some small differences between AR1300 (De'Arnise Hold) and 1304 (De'Arnise Hold rebuild). for instance, the door at x=1280; y=500 does not exist in AR1300 but exist for AR1304
however, in AR1304N, this door does not exist.

**Comment by weigo87** [comment]
Thanks TotoR. Problem solide.
