### ISSUE TITLE
AR4000, too dark with night map

### ISSUE THREAD

**Issue by TotoR115** [SpellholdStudios/BGGOEET#5]
@weigo87,

At night, the Tethyr forest map (AR4000 of ToB), is really too dark: PC and NPC are totally black (without infra). 
It seems to be linked to the AR4000LN.bmp (light map).

Cheers

**Comment by weigo87** [comment]
Problem is fixed. I uploaded a new AR4000LN.bmp for EE and non-EE Version

**Comment by TotoR115** [comment]
@weigo87,

I have installed the last version (262cdea) and on oBG2 (don't know for EE) when in AR4000 all sprite are green...

It seems that the light map is the culpit but maybe there is more.

Cheers

**Comment by weigo87** [comment]
I'll have a look next week, I'm on a business trip right now

**Comment by weigo87** [comment]
That was not so easy to solve. It did not take me an edited AR4000LN.bmp file for the non-ee version. Had to take the day version now, and then it worked.

**Comment by TotoR115** [comment]
That what I use when playing... the map is already dark, so maybe the LN is too dark...
The only draw back I think is that it makes NPC at night as in day.
I can't test anything; I am out for a few weeks, but when I'm back, I will try.

**Comment by TotoR115** [comment]
@weigo87 

I have found the culprit. The AR4000LN.BMP is in 8 bits instead of 24 bits, this leads to have back NPC (or red or green...).

If you changed it in 24 bits, it would work (see : https://drive.google.com/file/d/12vYg03vOGRJoffVDmhT0sYhD9XfleMyU/view?usp=drive_link). However, it seems to bright for a night map; the dif between day and night is not so visible on NPC.

So I have reworked it (see: https://drive.google.com/file/d/1xUUuox5OVA3v6VOqecmADL0MfMuF3n-a/view?usp=drive_link). With this one it feels more day/night. 

Anyway, It is up to you.

Cheers

**Comment by weigo87** [comment]
Thank you very much for your help. I will include your AR4000LN.bmp in the next update/commit.
The only strange thing is that all other XXXXLN.bmps are in 8 bit and also work. But we certainly don't want to question this any further as long as everything works :)
I still have to repair the AR7621, then the next commit will go online. Unfortunately my free time is much less than in the last six months, so it's not going quite as fast.

Cheers
